services:
  mysql:
    image: mysql:8.0
    container_name: viteetgourmand_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password_dev
      MYSQL_DATABASE: mydb
      MYSQL_USER: traiteur_user
      MYSQL_PASSWORD: password123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:7.0
    container_name: viteetgourmand_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
