version: '3.8'

services:
  api:
    build: .
    container_name: traiteur_api
    restart: always
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
      - DB_HOST=mysql_db
      - DB_USER=traiteur_user
      - DB_PASS=password123
      - DB_NAME=mydb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    container_name: traiteur_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: mydb
      MYSQL_USER: traiteur_user
      MYSQL_PASSWORD: password123
    ports:
      - "3307:3306"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - .db_data:/var/lib/mysql

  mongo_db:
    image: mongo:latest
    container_name: traiteur_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - .mongo_data:/data/db
